name: Compile and Run
on:
  workflow_dispatch:

permissions: 
  actions: read
  security-events: write

jobs:
   CI_test_run: 
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'    

      - name: Install system packages
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install libpython3.9 libtinfo5

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: ./hello_vsi/vcpkg-configuration.json

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
  
      - name: Build
        run: |
          echo "Building get started example ..."
          cbuild ${{ github.workspace }}/hello_vsi/hello_vsi.csolution.yml -c .event+Corstone_310 --packs --update-rte --toolchain GCC

      - name: Execute
        run: |
          echo "Running get started example ..."
          FVP_Corstone_SSE-310 -a ${{ github.workspace }}/hello_vsi/out/hello_vsi/Corstone_300/event/hello_vsi.elf -C mps3_board.v_path=./source/VSI/data_sensor/python/
